# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf0478a7b097715a4572f356c832df05543705f8ac6fa9fc891d8306601ffe74ad40c39f3edae91167037db81180eaabcb080fcd8c099aa2e5317c1d37393ac

test:
  secret_key_base: 1648bcc825523d658d4612a87f927b06b34b7f697dc8e2ce9b90997cbc968c5c04acbb0ddf5ae5f60676c21216ab74d5c3c4ba8b155318989ed7d6222a3d4a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
